version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2-browsers

    working_directory: ~/resume-nuxt

    steps:
      # 1
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      # 2
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      # 3
      - run:
          name: Nuxt3 Build
          command: npm run generate
      - save_cache:
          key: nuxt3-public-cache-{{ .Branch }}
          paths:
            - ./.output/public
      # 4
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome version
          command: |
            google-chrome --version
            chromedriver --version
      - save_cache:
          key: nuxt3-public-cache-{{ .Branch }}
          paths:
            - ./.output/public
      # 5
      - run:
          name: Insert CSS into HTML
          command: node ci/insertStyles.js
      - run:
          name: Save index to PDF
          command: bash ci/pdf.sh
      - save_cache:
          key: nuxt3-public-cache-{{ .Branch }}
          paths:
            - ./.output/public
      # 6
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=./.output/public

workflows:
  netlify:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
